---
name: extractor
description: Run Extractor

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry with pip
      shell: bash
      run: |
        pip install poetry

    - name: Install python libraries
      shell: bash
      run: |
        cd apps/extractor
        poetry config virtualenvs.create false
        poetry install --only main --no-interaction

    - name: Run Extractor
      shell: bash
      run: |
        cd apps/extractor
        PYTHONPATH=. poetry run python src/main.py
