---
name: refresh-api-docs-vector-index
description: Refresh API Docs for Chatbot LLamaindex Vector Index

inputs:
  aws_region:
    description: 'The AWS region selected'
    required: false
    default: 'eu-south-1'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: kishaningithub/setup-python-amazon-linux@282d998c8f2c4678ac4f872e4dc3b7d167b59fa7  # v1
      with:
        python-version: '3.12'

    - name: Install poetry with pip
      shell: bash
      run: |
        pip install poetry

    - name: Install python libraries
      shell: bash
      run: |
        cd apps/chatbot-index
        poetry config virtualenvs.create false
        poetry install --only main --no-interaction

    - name: Refresh API Docs in Vector Index
      shell: bash
      run: |
        cd apps/chatbot-index
        PYTHONPATH=. poetry run python src/modules/refresh_api_docs.py