name: upload-nextjs-bundle-stats
description: Upload NextJS bundle stats

inputs:
  path_to_nextjs_folder:
    description: 'The path to reach the NextJS folder (e.g. ./apps/website)'
    required: true
  upload_path:
    description: 'The path where the report should be uploaded'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Analyze bundle
      working-directory: ${{ inputs.path_to_nextjs_folder }}
      shell: bash
      run: npx -p nextjs-bundle-analysis@0.5.0 report

    - name: Upload bundle
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: bundle
        path: ${{ inputs.upload_path }}
