documentation:
  path: ../nextjs-website/out

vector_index:
  path: index
  chunk_sizes: [2816, 704, 176]
  chunk_overlap: 20
  redis_url: redis://localhost:6379

models:
  model_id: amazon.titan-text-express-v1
  emded_model_id: cohere.embed-multilingual-v3
  temperature: 0.3
  topP: 1.
  max_tokens: 784

retriever:
  similarity_top_k: 7
  similarity_cutoff: 0.55
  response_mode: compact
  verbose: False