documentation:
  path: build-devp/out

vector_index:
  path: index
  chunk_sizes: [2816, 704, 176]
  chunk_overlap: 20
  use_redis: True
  use_s3: False

models:
  provider: aws
  model_id: mistral.mistral-large-2402-v1:0
  emded_model_id: cohere.embed-multilingual-v3
  temperature: 0.5
  topP: 0.95
  max_tokens: 784

engine:
  similarity_top_k: 5
  similarity_cutoff: 0.55
  response_mode: compact
  verbose: False
  use_async: True
  streaming: False
