name: Generate SOAP API Metadata
description: Gene

inputs:
  soap-api-directory:
    description: Directory
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate wsdl.xml index JSON
      shell: bash
      run: |
        root_dir="${{ inputs.soap-api-directory }}"
        output_json="soap-api-metadata.json"
        tmpfile=$(mktemp)
        echo "[" > "$tmpfile"
        first=1
        for repo in "$root_dir"/*; do
          [ -d "$repo" ] || continue
          repo_name=$(basename "$repo")
          mapfile -t wsdl_files < <(find "$repo" -type f -name '*.wsdl.xml')
          if [ "${#wsdl_files[@]}" -gt 0 ]; then
            # Build array of relative paths
            rel_paths=()
            for f in "${wsdl_files[@]}"; do
              rel_path=$(realpath --relative-to="$root_dir" "$f")
              rel_paths+=("\"$rel_path\"")
            done
            rel_paths_joined=$(IFS=,; echo "${rel_paths[*]}")
            # Output JSON object
            [ $first -eq 1 ] || echo "," >> "$tmpfile"
            first=0
            echo "  {\"dirName\": \"$repo_name\", \"contentS3Paths\": [${rel_paths_joined}]}" >> "$tmpfile"
          fi
        done
        echo "]" >> "$tmpfile"
        mv "$tmpfile" "$output_json"
        mv "$output_json" "$root_dir"
        echo "Generated $output_json"
