receivers:
  telemetryapi:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: eu-south-1

service:
  pipelines:
    traces:
      receivers: [otlp, telemetryapi]
      exporters: [logging, awsxray]