receivers:
  telemetryapi:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: eu-south-1

service:
  pipelines:
    traces:
      receivers: [otlp, telemetryapi]
      exporters: [logging, awsxray]