name: download-gitbook-docs
description: Download docs from GitBook

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Setup node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Download GitBook docs
      shell: bash
      run: npm run download-docs -w nextjs-website
