/* eslint-disable functional/immutable-data */
/* eslint-disable functional/no-loop-statements */
/* eslint-disable functional/no-expression-statements */
/* eslint-disable functional/no-throw-statements */
import fs from 'node:fs';
import path from 'node:path';

import mjml2html from 'mjml';
import { minify } from 'html-minifier-next';

import { SUPPORTED_LOCALES } from '../src/i18n/locales';
import { EMAIL_TEMPLATE_BUILDERS } from '../src/templates/template-sources';

const defaultMinificationOptions = {
  caseSensitive: true,
  collapseWhitespace: true,
  minifyCSS: true,
  removeEmptyAttributes: true,
} as const;

const outputFilePath = path.join(
  __dirname,
  '..',
  'src',
  'templates',
  'generated',
  'precompiled-email-templates.ts'
);

type BuildTemplate = (locale: string) => string;

const compileTemplate = async (
  buildTemplate: BuildTemplate,
  locale: string
): Promise<string> => {
  const { errors, html } = mjml2html(buildTemplate(locale), {
    validationLevel: 'soft',
  });

  if (html.length === 0) {
    throw new Error(
      `Unable to compile ${
        buildTemplate.name || 'email template'
      } for locale ${locale}`
    );
  }

  if (errors.length > 0) {
    console.warn(
      `MJML validation warnings for ${
        buildTemplate.name || 'email template'
      } (${locale}): ${errors.map(({ message }) => message).join(', ')}`
    );
  }

  return minify(html, defaultMinificationOptions);
};

const buildTemplates = async (): Promise<
  Record<string, Record<string, string>>
> => {
  const precompiledTemplates: Record<string, Record<string, string>> = {};

  for (const [templateId, buildTemplate] of Object.entries(
    EMAIL_TEMPLATE_BUILDERS
  ) as ReadonlyArray<readonly [string, BuildTemplate]>) {
    precompiledTemplates[templateId] = {};

    for (const locale of SUPPORTED_LOCALES) {
      precompiledTemplates[templateId][locale] = await compileTemplate(
        buildTemplate,
        locale
      );
    }
  }

  return precompiledTemplates;
};

const writeTemplatesFile = async (): Promise<void> => {
  const precompiledTemplates = await buildTemplates();
  const outputContents = `/* This file is generated by scripts/generate-email-templates.ts. */
export const PRECOMPILED_EMAIL_TEMPLATES = ${JSON.stringify(
    precompiledTemplates,
    null,
    2
  )} as const;
`;

  fs.mkdirSync(path.dirname(outputFilePath), { recursive: true });
  fs.writeFileSync(outputFilePath, outputContents);
};

writeTemplatesFile().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
