---
name: structured-data-cleaner

services:
  motoserver:
    image: motoserver/moto:5.1.21@sha256:93ad54da7badce7f9c13e5e6439c93564c764663c42872d2c39f718aa484047a
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/moto-api/"]
      interval: 2s
      timeout: 5s
      retries: 10

  s3-init:
    build:
      context: .
      dockerfile: docker/app.local.Dockerfile
    command: /app/scripts/s3-init.sh
    env_file: .env
    volumes:
      - ./docker/files/.aws:/home/appuser/.aws
      - ./docker/files/s3:/app/files/s3
    depends_on:
      motoserver:
        condition: service_healthy

  parser:
    build:
      context: ../../
      dockerfile: apps/parser/docker/app.local.Dockerfile
    command: /app/apps/parser/scripts/run.pipeline.sh
    env_file: ../parser/.env
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CHB_INDEX_ID=${CHB_INDEX_ID}
      - URLS=${URLS}
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
    depends_on:
      s3-init:
        condition: service_completed_successfully

  extractor:
    build:
      context: ../extractor
      dockerfile: docker/app.local.Dockerfile
    command: /app/scripts/run.pipeline.sh
    env_file: ../extractor/.env
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CHB_INDEX_ID=${CHB_INDEX_ID}
      - URLS=${URLS}
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
    depends_on:
      s3-init:
        condition: service_completed_successfully

  structured-data-cleaner:
    build:
      context: .
      dockerfile: docker/app.local.Dockerfile
    command: python src/main.py
    env_file: .env
    volumes:
      - ./docker/files/.aws:/home/appuser/.aws
    depends_on:
      s3-init:
        condition: service_completed_successfully
