name: Build NextJS website
description: Build NextJS website

inputs:
  environment:
    description: 'The target environment'
    default: 'dev'
    required: false
  path_to_gitbook_docs:
    description: 'The absolute path to GitBook content'
    required: true
  cookie_domain_script:
    description: 'The data-domain-script code needed by cookie script from One Trust'
    required: false
  cookie_script_url:
    description: 'The URL of the cookie script from One Trust'
    required: false
  cookie_category:
    description: 'The category of the cookie script from One Trust'
    required: false
  allow_crawler:
    description: 'Allow crawler to index the website, by default are not allowed'
    required: false
  cognito_user_pool_id:
    description: 'The id of the User Pool on Cognito, needed for the authentication'
    required: true
  cognito_identity_pool_id:
    description: 'The id of the Identity Pool on Cognito, needed for the authorization'
    required: true
  cognito_app_client_id:
    description: 'The App Client registered on Cognito'
    required: true
  cognito_aws_region:
    description: 'The region where Cognito has been deployed. Default set to Milan region'
    required: false
    default: 'eu-south-1'
  webinar_question_lifetime_in_seconds:
    description: 'The lifetime of each question expressed in seconds'
    required: true
  strapi_endpoint:
    description: 'The endpoint to invoke to fetch data from Strapi'
    required: true
  strapi_api_token:
    description: 'The API key to use to invoke Strapi endpoint'
    required: true
  fetch_from_strapi:
    description: 'If true, then fetch content from Strapi; otherwise, use only static contents'
    required: false
    default: 'false'
  chatbot_active:
    description: 'If true, then the chatbot is visible; otherwise, the chatbot is hidden'
    required: false
    default: 'false'
  chatbot_host:
    description: 'The host of the chatbot'
    required: true


runs:
  using: "composite"
  steps:
    - name: Download GitBook docs
      uses: actions/checkout@v4
      with:
        repository: pagopa/devportal-docs
        ref: docs/from-gitbook
        path: apps/nextjs-website/checkout_path
        fetch-depth: 1
    
    - name: Update docs folder
      shell: bash
      run: npm run update-docs-ci -w nextjs-website

    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        NEXT_PUBLIC_ENVIRONMENT: ${{ inputs.environment }}
        PATH_TO_GITBOOK_DOCS: ${{ inputs.path_to_gitbook_docs }}
        NEXT_PUBLIC_COOKIE_DOMAIN_SCRIPT: ${{ inputs.cookie_domain_script }}
        NEXT_PUBLIC_COOKIE_SCRIPT_URL: ${{ inputs.cookie_script_url }}
        NEXT_PUBLIC_COOKIE_CATEGORY: ${{ inputs.cookie_category }}
        ALLOW_CRAWLER: ${{ inputs.allow_crawler }}
        NEXT_TELEMETRY_DISABLED: '1'
        NEXT_PUBLIC_COGNITO_USER_POOL_WEB_CLIENT_ID: ${{ inputs.cognito_app_client_id }}
        NEXT_PUBLIC_COGNITO_REGION: ${{ inputs.cognito_aws_region }}
        NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ inputs.cognito_user_pool_id }}
        NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID: ${{ inputs.cognito_identity_pool_id }}
        NEXT_PUBLIC_CHATBOT_HOST: ${{ inputs.chatbot_host }}
        NEXT_PUBLIC_CHAT_MAX_HISTORY_MESSAGES: ${{ inputs.chat_max_history_messages }}
        NEXT_PUBLIC_WEBSITE_NAME: ${{ inputs.website_name }}
        NEXT_PUBLIC_ORGANIZATION_NAME: ${{ inputs.organization_name }}
        NEXT_PUBLIC_ORGANIZATION_LOGO: ${{ inputs.organization_logo }}
        NEXT_PUBLIC_ORGANIZATION_SOCIAL_LINKS: ${{ inputs.organization_social_links }}
        NEXT_PUBLIC_CHATBOT_ACTIVE: ${{ inputs.chatbot_active }}
        NEXT_PUBLIC_MATOMO_SCRIPT_SRC: ${{ inputs.matomo_script_src }}
        STRAPI_ENDPOINT: ${{ inputs.strapi_endpoint }}
        STRAPI_API_TOKEN: ${{ inputs.strapi_api_token }}
        FETCH_FROM_STRAPI: ${{ inputs.fetch_from_strapi }}
      shell: bash
      run: |
        npm run build -w nextjs-website
        echo "Available storage after build:"
        sudo df -h
