name: Build NextJS website
description: Build NextJS website

inputs:
  environment:
    description: 'The target environment'
    default: 'dev'
    required: false
  path_to_gitbook_docs:
    description: 'The absolute path to GitBook content'
    required: true
  cookie_domain_script:
    description: 'The data-domain-script code needed by cookie script from One Trust'
    required: false
  allow_crawler:
    description: 'Allow crawler to index the website, by default are not allowed'
    required: false

runs:
  using: "composite"
  steps:
    - name: Fetch docs from GitBook
      shell: bash
      run: npm run download-docs -w nextjs-website

    - name: Restore NextJS cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ${{ github.workspace }}/apps/nextjs-website/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        PATH_TO_GITBOOK_DOCS: ${{ inputs.path_to_gitbook_docs }}
        COOKIE_DOMAIN_SCRIPT: ${{ inputs.cookie_domain_script }}
        ALLOW_CRAWLER: ${{ inputs.allow_crawler }}
        NEXT_TELEMETRY_DISABLED: '1'
      shell: bash
      run: npm run build -w nextjs-website
