name: build-website
description: Build NextJS website

inputs:
  environment:
    description: 'The target environment'
    default: 'dev'
    required: false
  path_to_gitbook_docs:
    description: 'The absolute path to GitBook content'
    required: true
  cookie_domain_script:
    description: 'The data-domain-script code needed by cookie script from One Trust'
    required: false
  disable_next_telemetry:
    description: 'True to disable NextJS tracking telemetry'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Node.js
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Compile packages
      shell: bash
      run: npm run compile

    - name: Fetch docs from GitBook
      shell: bash
      run: npm run download-docs -w nextjs-website

    - name: Restore NextJS build
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      id: restore-build-cache
      with:
        path: ${{ github.workspace }}/apps/nextjs-website/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        PATH_TO_GITBOOK_DOCS: ${{ inputs.path_to_gitbook_docs }}
        COOKIE_DOMAIN_SCRIPT: ${{ inputs.cookie_domain_script }}
        NEXT_TELEMETRY_DISABLED: ${{ inputs.disable_next_telemetry == 'true' && '1' || '0' }}
      shell: bash
      run: npm run build -w nextjs-website
