name: Build NextJS website
description: Build NextJS website

inputs:
  environment:
    description: 'The target environment'
    default: 'dev'
    required: false
  path_to_gitbook_docs:
    description: 'The absolute path to GitBook content'
    required: true
  cookie_domain_script:
    description: 'The data-domain-script code needed by cookie script from One Trust'
    required: false

runs:
  using: "composite"
  steps:
    - name: Fetch docs from GitBook
      shell: bash
      run: npm run download-docs -w nextjs-website

    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        PATH_TO_GITBOOK_DOCS: ${{ inputs.path_to_gitbook_docs }}
        COOKIE_DOMAIN_SCRIPT: ${{ inputs.cookie_domain_script }}
        NEXT_TELEMETRY_DISABLED: '1'
      shell: bash
      run: npm run build -w nextjs-website
