name: Add Stylesheet Reference to WSDLs
description: Add a stylesheet reference to WSDL files in the devportal-api directory

inputs:
  dir:
    description: Directory to search for WSDL files
    required: true

runs:
  using: "composite"
  steps:
    - name: Find and Update WSDL Files
      shell: bash
      run: |
        find "${{ inputs.dir }}" -type f -name "*.wsdl" | while read -r file; do
          if ! grep -q '<?xml-stylesheet type="text/xsl" href="../wsdl-viewer/wsdl-viewer.xsl"?>' "$file"; then
            sed -i '2i<?xml-stylesheet type="text/xsl" href="../wsdl-viewer/wsdl-viewer.xsl"?>' "$file"
          fi
        done
