name: Check NextJS bundle size
description: Check NextJS bundle size

inputs:
  path_to_nextjs_folder:
    description: 'The path to reach the NextJS folder (e.g. ./apps/website)'
    required: true
  upload_path:
    description: 'The path where the report should be uploaded'
    required: true

runs:
  using: "composite"
  steps:
    # Here's the first place where next-bundle-analysis' own script is used
    # This step pulls the raw bundle stats for the current bundle
    - name: Generate bundle report
      working-directory: ${{ inputs.path_to_nextjs_folder }}
      shell: bash
      run: npx -p nextjs-bundle-analysis@0.5.0 report

    - name: Upload bundle
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: bundle
        path: ${{ inputs.upload_path }}

    - name: Download base branch bundle stats
      id: base-branch-stats
      uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
      if: success() && github.event.number
      with:
        branch: ${{ github.event.pull_request.base.ref }}
        path: apps/nextjs-website/.next/analyze/base
        if_no_artifact_found: warn

    # If no bundle found for base branch, drop a comment on the PR saying that.
    - name: Create comment for no bundle found
      uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9 # v2.7.0
      if: steps.base-branch-stats.outputs.found_artifact == 'false'
      with:
        header: next-bundle-analysis
        recreate: true
        message: |
          Bundle not found for branch `${{ github.event.pull_request.base.ref }}`.
          It wasn't possible to compare bundles size.

    # And here's the second place - this runs after we have both the current and
    # base branch bundle stats, and will compare them to determine what changed.
    # There are two configurable arguments that come from package.json:
    #
    # - budget: optional, set a budget (bytes) against which size changes are measured
    #           it's set to 350kb here by default, as informed by the following piece:
    #           https://infrequently.org/2021/03/the-performance-inequality-gap/
    #
    # - red-status-percentage: sets the percent size increase where you get a red
    #                          status indicator, defaults to 20%
    #
    # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
    # entry in your package.json file.
    - name: Compare with base branch bundle
      if: steps.base-branch-stats.outputs.found_artifact == 'true' && success() && github.event.number
      working-directory: ${{ inputs.path_to_nextjs_folder }}
      shell: bash
      run: npx -p nextjs-bundle-analysis@0.5.0 compare

    - name: Get Comment Body
      id: get-comment-body
      if: steps.base-branch-stats.outputs.found_artifact == 'true' && success() && github.event.number
      working-directory: ${{ inputs.path_to_nextjs_folder }}
      shell: bash
      run: |
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT

    - name: Create comment with bundle size report
      uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9 # v2.7.0
      if: steps.base-branch-stats.outputs.found_artifact == 'true' && success()
      with:
        header: next-bundle-analysis
        recreate: true
        message: ${{ steps.get-comment-body.outputs.body }}
