receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 50

exporters:
  awsxray:
    region: 'eu-south-1'
  awsemf:
    region: 'eu-south-1'
    namespace: 'opennext'
    log_group_name: '/aws/lambda/devportal-d-website-opnext-server-lambda-01'
    log_stream_name: 'instrumentation'
    dimension_rollup_option: 'NoDimensionRollup'

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]