name: Setup Terraform
description: Setup Terraform

inputs:
  environment:
    description: 'The environment where to execute commands'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Terraform version
      shell: bash
      working-directory: .infrastructure
      run: echo "TERRAFORM_VERSION=`cat .terraform-version`" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Check Terraform format
      shell: bash
      run: terraform fmt -check

    - name: Terraform Init
      shell: bash
      working-directory: .infrastructure
      run: ./terraform.sh init ${{ inputs.environment }}
