/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiPluginSso from "strapi-plugin-sso/strapi-admin";
import updateStaticContent from "strapi-plugin-update-static-content/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor: ckeditor,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-plugin-sso": strapiPluginSso,
    "update-static-content": updateStaticContent,
  },
});
