services:
  api:
    build:
      context: ..
      dockerfile: docker/app.local.Dockerfile
    env_file: ../.env.local
    command: "./scripts/run.local.sh"
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - ./files/.aws:/root/.aws
      - ../../nextjs-website/out:/app/build-devp/out
    depends_on:
      redis:
        condition: service_started
      dynamodb:
        condition: service_started
    networks:
      - ntw

  dynamodb:
    image: amazon/dynamodb-local:2.5.2@sha256:d7ebddeb60fa418bcda218a6c6a402a58441b2a20d54c9cb1d85fd5194341753
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=local
    ports:
      - "8000:8000"
    networks:
      - ntw

  redis:
    image: redis/redis-stack:7.2.0-v13@sha256:2b000b938e407d14acafa9b7affd4c5a94ceeec572b25b15dcef0d3a6c064d7e
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - ntw

  create_index:
    build:
      context: ..
      dockerfile: docker/app.local.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - ../../nextjs-website/out:/app/build-devp/out
    command: "python src/modules/create_vector_index.py --params config/params.yaml"
    tty: true
    depends_on:
      redis:
        condition: service_started
    networks:
      - ntw

networks:
  ntw:
