---
services:
  api:
    build:
      context: ..
      dockerfile: docker/app.local.Dockerfile
    command: "./scripts/run.local.sh"
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - ./files/.aws:/root/.aws
      - ../../nextjs-website/out:/app/build-devp/out
    depends_on:
      redis:
        condition: service_started
      dynamodb:
        condition: service_started
      langfuse:
        condition: service_started
    env_file: ../.env.local
    networks:
      - ntw

  postgres:
    image: postgres:17.2-alpine@sha256:d37d2c160d34430877c802e5adc22824a2ad453499db9bab1a2ceb2be6c1a46f
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ../.env.local
    networks:
      - ntw

  dynamodb:
    image: amazon/dynamodb-local:2.5.2@sha256:d7ebddeb60fa418bcda218a6c6a402a58441b2a20d54c9cb1d85fd5194341753
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=local
    ports:
      - "8000:8000"
    networks:
      - ntw

  redis:
    image: redis/redis-stack:7.2.0-v13@sha256:2b000b938e407d14acafa9b7affd4c5a94ceeec572b25b15dcef0d3a6c064d7e
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - ntw

  create_index:
    build:
      context: ..
      dockerfile: docker/app.local.Dockerfile
    command: "python src/modules/create_vector_index.py --params config/params.yaml"
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - ../../nextjs-website/out:/app/build-devp/out
    tty: true
    depends_on:
      redis:
        condition: service_started
    env_file: ../.env.local
    networks:
      - ntw

  langfuse:
    image: langfuse/langfuse:2@sha256:79f4df5c79f421810c45c89bedda3ff381723b1573dcfe98b988736ff8e9d16e
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"
    env_file: ../.env.local
    networks:
      - ntw

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ntw:
