services:
  master:
    image: locustio/locust:2.32.1@sha256:d0bd7649b89fb2ee981e382d6e9ae2932d898110707943ecff0ef108569b6a5f
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H ${HOST} -u ${NUM_USERS} -r ${SPAWN_RATE}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    image: locustio/locust:2.32.1@sha256:d0bd7649b89fb2ee981e382d6e9ae2932d898110707943ecff0ef108569b6a5f
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
