services:
  master:
    image: locustio/locust:2.32.1
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H ${HOST} -u ${NUM_USERS} -r ${SPAWN_RATE}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    image: locustio/locust:2.32.1
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
