---
name: chatbot
description: Create Chatbot LLamaindex Vector Index

inputs:
  aws_region:
    description: 'The AWS region selected'
    required: false
    default: 'eu-south-1'
  chatbot_lambda_name:
    description: the name of the chatbot lambda function
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: kishaningithub/setup-python-amazon-linux@282d998c8f2c4678ac4f872e4dc3b7d167b59fa7  # v1
      with:
        python-version: '3.12'

    - name: Install poetry with pip
      shell: bash
      run: |
        pip install poetry

    - name: Install python libraries
      shell: bash
      run: |
        cd apps/chatbot-index
        poetry config virtualenvs.create false
        poetry install --only main --no-interaction

    - name: Install chrome dependencies
      shell: bash
      run: |
        cd apps/chatbot-index
        bash ./docker/chrome-installer.sh

    - name: Run tests
      shell: bash
      run: |
        cd apps/chatbot-index
        PYTHONPATH=. poetry run ./src/modules/pytest

    - name: Create Vector Index
      shell: bash
      run: |
        cd apps/chatbot-index
        PYTHONPATH=. poetry run python src/modules/create_vector_index.py

    - name: Restart backend lambda function
      env:
        CHATBOT_LAMBDA_NAME: ${{ inputs.chatbot_lambda_name }}
      shell: bash
      run: |
        aws lambda update-function-code --function-name "${{ env.CHATBOT_LAMBDA_NAME }}" --image-uri $(aws lambda get-function --function-name "${{ env.CHATBOT_LAMBDA_NAME }}" --query 'Code.ImageUri' --output text)
