---
name: chatbot
description: Create Chatbot LLamaindex Vector Index

inputs:
  aws_region:
    description: 'The AWS region selected'
    required: false
    default: 'eu-south-1'
  chatbot_lambda_name:
    description: the name of the chatbot lambda function
    required: true
    default: ''
  static:
    description: 'Whether to create vector index using static data'
    required: true
    default: 'true'
  dynamic:
    description: 'Whether to create vector index using dynamic data'
    required: true
    default: 'true'
  api:
    description: 'Whether to create vector index using api data'
    required: true
    default: 'true'
  structured:
    description: 'Whether to create vector index using structured data'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: kishaningithub/setup-python-amazon-linux@282d998c8f2c4678ac4f872e4dc3b7d167b59fa7  # v1
      with:
        python-version: '3.12'

    - name: Install poetry with pip
      shell: bash
      run: |
        pip install poetry

    - name: Install python libraries
      shell: bash
      run: |
        cd apps/chatbot-index
        poetry config virtualenvs.create false
        poetry install --only main --no-interaction

    - name: Install chrome dependencies
      shell: bash
      run: |
        cd apps/chatbot-index
        bash ./docker/chrome-installer.sh

    - name: Create Vector Index
      shell: bash
      run: |
        cd apps/chatbot-index
        PYTHONPATH=. poetry run python src/modules/create_vector_index.py ${{ inputs.static == true && ' --static' || '' }} ${{ inputs.dynamic == true && ' --dynamic' || '' }} ${{ inputs.api == true && ' --api' || '' }} ${{ inputs.structured == true && ' --structured' || '' }} --clean-redis
