---
name: chatbot
description: Recreate Chatbot LLamaindex Vector Index

inputs:
  aws_region:
    description: 'The AWS region selected'
    required: false
    default: 'eu-south-1'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: kishaningithub/setup-python-amazon-linux@282d998c8f2c4678ac4f872e4dc3b7d167b59fa7  # v1
      with:
        python-version: '3.12'

    - name: Install poetry with pip
      shell: bash
      run: |
        pip install poetry

    - name: Install python libraries
      shell: bash
      run: |
        cd apps/chatbot
        poetry config virtualenvs.create false
        poetry install --only main --no-interaction

#    - name: Run tests
#      run: |
#        cd apps/chatbot
#        poetry run pytest
#        coverage report
#

    - name: Create Vector Index
      shell: bash
      run: |
        cd apps/chatbot
        PYTHONPATH=. CHB_DOCUMENTATION_DIR=${{ github.workspace }}/apps/nextjs-website/out poetry run python src/modules/create_vector_index.py --params config/params.yaml

    - name: Restart backend lambda function
      shell: bash
      run: |
        aws lambda update-function-configuration --function-name ${{ env.CHATBOT_LAMBDA_NAME }}
