name: chatbot
description: Recreate Chatbot LLamaindex Vector Index

inputs:
  aws_region:
    description: 'The AWS region selected'
    required: false
    default: 'eu-south-1'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Python
      uses: kishaningithub/setup-python-amazon-linux@282d998c8f2c4678ac4f872e4dc3b7d167b59fa7 # v1
      with:
        python-version: '3.12'

    - name: Install and configure Poetry
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      with:
        version: 1.8.3
        virtualenvs-create: false
        installer-parallel: true

    - name: Install python libraries
      shell: bash
      run: |
        cd apps/chatbot
        poetry install --no-interaction
    
#    - name: Run tests
#      run: |
#        cd apps/chatbot
#        poetry run pytest
#        coverage report
#

    - name: Create Vector Index
      shell: bash
      run: |
        cd apps/chatbot
        poetry run python src/modules/create_vector_index.py --params config/params.yaml
