name: Check PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:

  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Check PR is linked to Jira activity
        uses: ./.github/actions/link-pr-to-jira-activity
