name: Check PR branch up to date

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:

  check_branch_up_to_date:
    name: Verify branch is up to date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'

      - name: Check PR branch is updated
        uses: ./.github/actions/branch-up-to-date
