name: CI

on:
  push:
    tags: '*'
  pull_request:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile_test:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Check lock file is up to date
        run: npx -y package-lock-utd@1.1.3

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Lint code
        run: npm run lint

      - name: Execute tests
        run: npm run test

  build_website:
    name: Build static website
    runs-on: ubuntu-latest

    needs:
      - compile_test

    steps:
      - name: Build static website
        uses: ./.github/actions/build-nextjs-website
        with:
          path_to_gitbook_docs: ${{ github.workspace }}/apps/nextjs-website/docs
          cookie_domain_script: ${{ secrets.COOKIE_DOMAIN_SCRIPT }}
          nextjs_telemetry: "1"

