name: CI

on:
  push:
    tags: '*'
  pull_request:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Check lock file is up to date
        run: npx -y package-lock-utd@1.1.3

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Download GitBook docs
        run: npm run download-docs -w nextjs-website

      - name: Lint code
        run: npm run lint

      - name: Execute tests
        run: npm run test

      - name: Build static website
        shell: bash
        env:
          PATH_TO_GITBOOK_DOCS: ${{ github.workspace }}/apps/nextjs-website/docs
          COOKIE_DOMAIN_SCRIPT: ${{ github.workspace }}/apps/nextjs-website/docs
          NEXT_TELEMETRY_DISABLED: "1"
        run: npm run build -w nextjs-website
