name: CI

on:
  push:
    tags: '*'
  pull_request:
    branches: '**'
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.node-version'
      - 'package.json'
      - 'tsconfig.json'
      - 'turbo.json'
      - '.github/workflows/**'
      - '!.github/workflows/infra-*'

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Lint code
        run: npm run lint

      - name: Execute tests
        run: npm run test
