name: CI

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile_test:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Check lock file is up to date
        run: npx -y package-lock-utd@1.1.3

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Lint code
        run: npm run lint

      - name: Execute tests
        run: npm run test
