name: CI

on:
  push:
    tags: '*'
  pull_request:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Compile
        run: yarn compile

      - name: Lint code
        run: yarn lint

      - name: Execute tests
        run: yarn test
