name: Code Review Infra

on:
  pull_request:
    branches: '**'
    # Run only if there are at least one change matching the following paths
    paths:
      - '.infrastructure/**'
      - '.github/workflows/code_review_infra.yaml'

defaults:
  run:
    shell: bash
    working-directory: .infrastructure

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  infrastructure_checks:
    strategy:
      matrix:
        environment: [dev, prod]
    name: Infra checks
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.JS
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: npm ci --audit=false --fund=false

      - name: Compile
        run: npm run compile -w cloudfront-functions

      - name: Configure AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws_region: 'eu-south-1'
          role_to_assume: ${{ secrets.IAM_ROLE }}

      - name: Set terraform version
        uses: ./.github/actions/setup-terraform
        with:
          environment: ${{ matrix.environment }}

      - name: Terraform Plan
        run: ./terraform.sh plan ${{ matrix.environment }}
