name: Code Review Infra

on:
  pull_request:
    branches: '**'
    # Run only if there are at least one change matching the following paths
    paths:
      - '.infrastructure/**'
      - '.github/workflows/code_review_infra.yaml'

defaults:
  run:
    shell: bash
    working-directory: .infrastructure

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  infrastructure_checks:
    strategy:
      matrix:
        environment: [dev, prod]
    name: Infra checks
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Restore cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Configure AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws_region: 'eu-south-1'
          role_to_assume: ${{ secrets.IAM_ROLE }}

      - name: Set terraform version
        run: |
          echo "TERRAFORM_VERSION=`cat .terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: |
          ./terraform.sh init ${{ matrix.environment }}

      - name: Terraform Plan
        run: |
          ./terraform.sh plan ${{ matrix.environment }}
