name: Generate Release Notes Metadata

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Generate release notes metadata for the given environment'
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod

# These permissions are needed to interact with GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  generate_metadata:
    name: Generate Release Notes Metadata
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: npm ci

      - name: Compile packages
        run: npm run compile

      - name: Configure AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws_region: eu-south-1
          role_to_assume: ${{ secrets.DEPLOY_IAM_ROLE }}

      - name: Generate release notes metadata
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
          S3_PATH_TO_GITBOOK_DOCS: ${{ vars.S3_PATH_TO_GITBOOK_DOCS || 'docs' }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          STRAPI_ENDPOINT: ${{ vars.STRAPI_ENDPOINT }}
          STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
          FETCH_FROM_STRAPI: ${{ vars.FETCH_FROM_STRAPI || 'true' }}
        run: npm run generate-release-notes-metadata -w gitbook-docs 