name: "Infra CI"

on:
  pull_request:
    branches: '**'
    # Run only if there are at least one change matching the following paths
    paths:
      - '.infrastructure/**'
      - '.github/workflows/*.yml'

defaults:
  run:
    shell: bash
    working-directory: .infrastructure

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform_plan:
    strategy:
      matrix:
        environment: [dev]
    name: Terraform plan
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
     
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Configure AWS Credentials
        env:
          AWS_REGION: eu-south-1
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set terraform version
        run: |
          echo "TERRAFORM_VERSION=`cat .terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: |
          ./terraform.sh init ${{ matrix.environment }}

      - name: Terraform Plan
        run: |
          ./terraform.sh plan ${{ matrix.environment }}
