name: 'Next.js Bundle Analysis'

on:
  pull_request:
  workflow_dispatch:

concurrency:
  # In case of multiple commits of same PR, the previous run of the Action will be deleted
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build NextJS Website
        uses: ./.github/actions/build-nextjs-website
        with:
          path_to_gitbook_docs: ${{ github.workspace }}/apps/nextjs-website/docs
          cookie_domain_script: ${{ secrets.COOKIE_DOMAIN_SCRIPT }}
          disable_next_telemetry: true

      # Here's the first place where next-bundle-analysis' own script is used
      # This step pulls the raw bundle stats for the current bundle
      - name: Generate NextJS bundle stats
        uses: ./.github/actions/upload-nextjs-bundle-stats
        with:
          path_to_nextjs_folder: ./apps/nextjs-website
          upload_path: apps/nextjs-website/.next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        id: base-branch-stats
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        if: success() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: apps/nextjs-website/.next/analyze/base
          if_no_artifact_found: warn

      # If no bundle found for base branch, drop a comment on the PR saying that.
      - name: Create comment for no bundle found
        uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9 # v2.7.0
        if: steps.base-branch-stats.outputs.found_artifact == 'false'
        with:
          header: next-bundle-analysis
          message: |
            Bundle not found for branch `${{ github.event.pull_request.base.ref }}`.
            It wasn't possible to compare bundles size.

      # And here's the second place - this runs after we have both the current and
      # base branch bundle stats, and will compare them to determine what changed.
      # There are two configurable arguments that come from package.json:
      #
      # - budget: optional, set a budget (bytes) against which size changes are measured
      #           it's set to 350kb here by default, as informed by the following piece:
      #           https://infrequently.org/2021/03/the-performance-inequality-gap/
      #
      # - red-status-percentage: sets the percent size increase where you get a red
      #                          status indicator, defaults to 20%
      #
      # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
      # entry in your package.json file.
      - name: Compare with base branch bundle
        if: steps.base-branch-stats.outputs.found_artifact == 'true' && success() && github.event.number
        working-directory: ./apps/nextjs-website
        run: npx -p nextjs-bundle-analysis@0.5.0 compare

      - name: Get Comment Body
        id: get-comment-body
        if: steps.base-branch-stats.outputs.found_artifact == 'true' && success() && github.event.number
        working-directory: ./apps/nextjs-website
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Create comment with bundle size report
        uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9 # v2.7.0
        if: steps.base-branch-stats.outputs.found_artifact == 'true' && success()
        with:
          header: next-bundle-analysis
          message: ${{ steps.get-comment-body.outputs.body }}
