name: SOAP API Repo Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment used as target'
        type: choice
        required: true
        default: dev
        options:
          - dev
          - uat
          - prod

# Permissions needed for AWS OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  sync_docs:
    name: Sync SOAP API to S3
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Fetch and clone SOAP APIs
        uses: ./.github/actions/clone-soap-api-repos
        with:
          soap-api-directory: ./soap-api
          strapi-endpoint: ${{ vars.STRAPI_ENDPOINT }}
          strapi-api-token: ${{ secrets.STRAPI_API_TOKEN }}

      - name: Copy WSDL Viewer Library to SOAP Repos
        uses: ./.github/actions/copy-wsdl-stylesheet-to-soap-repos
        with:
          stylesheet_path: ./apps/nextjs-website/public/wsdl-viewer
          soap_repos_path: ./soap-api

      - name: Add Stylesheet Reference to WSDLs
        uses: ./.github/actions/add-stylesheet-ref-to-wsdl
        with:
          dir: ./soap-api

      - name: Generate SOAP API metadata
        uses: ./.github/actions/generate-soap-api-metadata
        with:
          soap-api-directory: ./soap-api

      - name: Configure AWS Credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          aws_region: eu-south-1
          role_to_assume: ${{ secrets.DEPLOY_IAM_ROLE }}

      - name: Sync soap-api folder to S3
        run: |
          FIRST_LETTER="${{ inputs.environment }}" && FIRST_LETTER="${FIRST_LETTER:0:1}" && \
          aws s3 sync soap-api s3://devportal-${FIRST_LETTER}-website-static-content/soap-api --delete
